### ISSUE TITLE
Need to resolve duplicate institutions for Einstein med and several others

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#172] opened 2024-04-05 23:33 UTC
See https://portal.rcd-nexus.org/admin/nexus/institution/?q=einstein

User is affiliated with the wrong one

**Comment by plschmitz** [comment] 2024-04-05 23:41
Another for https://portal.rcd-nexus.org/admin/nexus/institution/?q=Case+Western+Reserve+University

**Comment by plschmitz** [comment] 2024-04-05 23:43
Weird one for University of Minnesota.  Should be University of Minnesota-Twin Cities

**Comment by plschmitz** [comment] 2024-04-05 23:50
Another one for Massachusetts Institute of Technology

**Comment by plschmitz** [comment] 2024-04-05 23:51
Another one for Weill Cornell Medical College

**Comment by plschmitz** [comment] 2024-04-05 23:53
Another for Stony Brook University

**Comment by plschmitz** [comment] 2024-04-06 00:02
Another for Rutgers

**Comment by plschmitz** [comment] 2024-04-06 00:08
Another for South Dakota State

**Comment by pphysch** [comment] 2024-06-03 22:13
This is caused by mismatch between CILogon and IPEDS representations of institutions.

1. Some CILogon and IPEDS institutions have mismatched/multiple URLs. For example, einsteinmed.org (CILogon HomePage) vs. einsteinmed.edu (IPEDS URL).
2. One CILogon IDP may provide for multiple separate IPEDS institutions, e.g. Rutgers which has 3 separate campuses.

To fix (1) we need to expand the matching algorithm, e.g. gather the different emails/URLs mentioned throughout the CILogon IDP record.

To fix (2) we need to reverse the IDP -> Institution FK, so that multiple institutions can point at the same IDP. Then we need to modify the login flow so that users with no current affiliation can pick one of the institutions related to their login IDP (or request a new one if N/A).

**Comment by plschmitz** [comment] 2024-08-09 17:17
Assigning back to you to plan and implement the change. We can discuss if there are considerations that may impact users (beyond fixing the problems).

**Comment by pphysch** [comment] 2024-09-03 23:08
I implemented a quick partial fix in [7393d6e](https://github.com/CaRCC/rcd-nexus-portal/commit/7393d6e9ffa5b55cae97ed87104de255479dcb01) which addresses some cases of both 1 and 2. 

For example, the MIT case should be fixed.

**Comment by pphysch** [comment] 2024-09-03 23:20
I also added `utils.data.merge_institutions` function in [29bf07f](https://github.com/CaRCC/rcd-nexus-portal/commit/29bf07f377d49d120447b62d35814da1faaed4fd) which we can later use to quickly merge institutions affected by these bugs.

**Comment by plschmitz** [comment] 2024-09-06 20:02
I created a migration to incorporate this functionality. Pushed to staging.

**Closed as completed** 2024-09-06 21:43 UTC
Labels: bug
